#!/bin/sh
#

# For RHEL Linux systems
# streamer          Start/Stop sync
#
# chkconfig: 35 98 10
# description: streamer service
# processname: streamer
# config:
# pidfile: /var/run/streamer.pid

# For Ubuntu Linux systems
### BEGIN INIT INFO
# Provides:          streamer
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start ZMQ streamer
# Description:       Start the streamer service to stream images via ZMQ
### END INIT INFO

. /etc/rc.status

# Requires Java >= 1.7
PATH=/usr/java/default/bin:$PATH
export PATH

USER=det
HOME=/opt/streamer
LOGFILE=/var/log/streamer
# Make sure that the ramdisk is writeable by the detector user!
RAMDISK=/tmp/ramdisk
PORT=8080

SU="su --login  $USER --command  "

touch $LOGFILE
chown $USER $LOGFILE

case "$1" in
start)
  # TODO Replace this with startproc command: startproc -f -p $PIDFILE $CRON_BIN
  $SU "PATH=/opt/jre/bin:$PATH $HOME/latest/bin/streamer -d $RAMDISK -p $PORT > $LOGFILE 2>&1 &"
  ;;
stop)
  # TODO replace this by killproc command: killproc -TERM -p $PIDFILE $CRON_BIN
  $SU "pkill -f 'java .* $HOME' >> $LOGFILE 2>&1 &"
  ;;
status)
  echo -n "Streamer: "
  checkproc $HOME/latest/bin/streamer
  rc_status -v
  ;;
restart)
  $0 stop
  $0 start
  ;;
*)
  echo "usage: $0 (start|stop|restart|help)"
esac